Implement an account protection mechanism (solve issue #98)
trebol-ecommerce/spring-boot-backend pull request #129
Opened 2022-10-09 10:40 UTC by mepox

This was an interesting one. I spent some time on it how to implement it as there are multiple ways to do it.

I decided to name this feature as "account protection" instead of using or making an account "root". Please review.

##### NOTE: I think the user(s) shouldn't able to disable (or enable) this account protection during runtime.

2022-10-10 21:40 UTC, bglamadrid requested changes
Greeting @mepox ! Thanks for your work into this issue. I see you've read through the code and got yourself a workaround to making it work. 

However, I'd like to step up the quality of this contribution. You can do better ⭐ I'll guide and help you get to its fruition, so please see the comments I've left for you below. I've tried to be brief, yet clear. I think you can totally handle this.

2022-10-11 13:17 UTC, NyorJa commented
> Hi @bglamadrid ! Please review.

I would like to check also @mepox

2022-10-11 14:35 UTC, NyorJa commented
Hi @mepox,

Please check the implementation of GenericDataCrudController class ""delete" method. BadInputException must be handle in the implementation controller classes.

2022-10-11 15:23 UTC, bglamadrid commented
@mepox, what IDE are you using? Does it support Project Lombok/did it ask you anything to set it up on your machine?

Yes, as I remember there are some methods I left only with an `UnsupportedOperationException` as there is still some features that I want this project to have.

2022-10-11 15:42 UTC, NyorJa commented on src/main/java/org/trebol/jpa/services/crud/UsersJpaCrudServiceImpl.java
> +    		if (user != null && user.getId() == securityProperties.getProtectedAccountId()) {
Please remove `user != null` since isPresent can handle the null check

2022-10-11 15:45 UTC, bglamadrid commented
> > @mepox, what IDE are you using? Does it support Project Lombok/did it ask you anything to set it up on your machine?
> > Yes, as I remember there are some methods I left only to throw a `UnsupportedOperationException`s, as there are still features to be worked on in this project.
> 
> @bglamadrid I use Eclipse and I just imported the project as a maven project as usual. Didn't ask anything.
> 
> See the screenshot: [screenshot](https://imgur.com/a/9qzsSk1)

[Check this tutorial](https://projectlombok.org/setup/eclipse) in order to install Project Lombok in your Eclipse IDE. That should get rid of the warnings and errors you're seeing.

2022-10-11 15:59 UTC, bglamadrid commented
> Thanks. I installed Lombok into Eclipse but nothing changed. Lombok is for extra annotations isn't it (I haven't used Lombok before)? Anyway the errors are still there...

Eclipse is a little bit quirky. There are some things that you should always try.

Did you close Eclipse and open it again? Did you try deleting those errors from that list (selecting them and pressing `Supr` or `Del`)? Did you try forcing a new project build?

2022-10-11 19:09 UTC, bglamadrid requested changes
@mepox, this PR is involving too many changes at once, mostly due to your use of the `BadInputException` class to raise the validation error. This feature really shouldn't really need to change nineteen files, but ten at most.

A better way to implement this would be to use a `RuntimeException` descendant; an unchecked exception that doesn't require declaration in each class & interface method signature unlike checked `Exception`s.

  - Say you create a `AccountProtectionViolationException` that extends `RuntimeException` (it can be similar to other custom `Exception` classes we have in this project).
  - Then raise that new class for the error behind your validation code, right in the `UsersJpaCrudServiceImpl`.
  - Then, remove all references to `BadInputException` that now exist outside of the classes you're directly working on; the controllers, their abstract superclass, interface, and same goes for the service's superclass & interface.

2022-10-11 20:45 UTC, bglamadrid approved these changes
Thank you once again @mepox, this involved a lot of changes. 

There are still some minor details that I want to emphasize, but those I will simply submit as new issues instead of blocking this PR any longer, for it is already accomplishing the objective 👌

2022-10-11 20:45 UTC, bglamadrid commented on src/main/java/org/trebol/jpa/services/ICrudJpaService.java
> + * @throws BadInputException
style: re-indent this line

2022-10-11 20:45 UTC, bglamadrid commented on src/main/java/org/trebol/jpa/services/crud/UsersJpaCrudServiceImpl.java
> +	super.delete(filters);
style: re-indent this line

2022-10-11 20:45 UTC, bglamadrid commented on src/test/java/org/trebol/jpa/services/crud/UsersJpaCrudServiceTest.java
>    }
test: decorate `instance` with `@InjectMocks` instead of manually initializing it

2022-10-11 20:45 UTC, bglamadrid commented on src/test/java/org/trebol/jpa/services/crud/UsersJpaCrudServiceTest.java
> +	assertThrows(AccountProtectionViolationException.class, () -> instance.delete(predicateMock));
style: fix code indentation

2022-10-11 20:45 UTC, bglamadrid commented on src/test/java/org/trebol/jpa/services/crud/UsersJpaCrudServiceTest.java
> +	};
test: use QueryDSL types to generate the required `Predicate`

2022-10-11 20:50 UTC, merged

2022-10-11 20:59 UTC, bglamadrid commented on src/test/java/org/trebol/jpa/services/GenericJpaCrudServiceTest.java
> +      throws EntityNotFoundException, BadInputException {
chore: remove this `BadInputException` as it is no longer needed