Update PeopleConverterJpaServiceImpl.java
trebol-ecommerce/spring-boot-backend pull request #195
Opened 2022-10-29 03:05 UTC by JellyBoonz

Merged the two if statements. Formatting changes to reduce code smell. No change in logic/behavior.

2022-10-29 08:59 UTC, NyorJa requested changes
I suggest use apache commons lang3 StringUtils.equals()

It has null checking and comparison

2022-10-29 18:56 UTC, JellyBoonz commented
I made changes to use StringUtils.equals(). Let me know if this is sufficient.

2022-10-29 19:25 UTC, NyorJa commented on src/main/java/org/trebol/jpa/services/conversion/PeopleConverterJpaServiceImpl.java
> +    if (!phone1.equals(null) && !target.getPhone1().equals(phone1)) {
Use apache commons lang 3..

`!StringUtils.equals(phone1, target.getPhone1())`

2022-10-30 02:26 UTC, bglamadrid commented
Sorry @JellyBoonz, PR #196 has this covered in full. I'll take that one. 
Still thank you very much. You can totally go for another good first issue like this if you want to 👍

2022-10-30 02:26 UTC, closed without merging